/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { KeyValueResponse } from '../model/keyValueResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TravelControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getExpenseByBranch
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpenseByBranchUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpenseByBranchUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpenseByBranchUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpenseByBranchUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpenseByBranch`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpenseByBusinessArea
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpenseByBusinessAreaUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpenseByBusinessAreaUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpenseByBusinessAreaUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpenseByBusinessAreaUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpenseByBusinessArea`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpenseByCostCenter
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpenseByCostCenterUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpenseByCostCenterUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpenseByCostCenterUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpenseByCostCenterUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpenseByCostCenter`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpenseByDesignation
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpenseByDesignationUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpenseByDesignationUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpenseByDesignationUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpenseByDesignationUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpenseByDesignation`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpenseByEmployeeGrade
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpenseByEmployeeGradeUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpenseByEmployeeGradeUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpenseByEmployeeGradeUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpenseByEmployeeGradeUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpenseByEmployeeGrade`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpensePerEmployeeByTime
     * 
     * @param endDate endDate
     * @param startDate startDate
     * @param employeeCount employeeCount
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpensePerEmployeeByTimeUsingPOST(endDate: string, startDate: string, employeeCount?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpensePerEmployeeByTimeUsingPOST(endDate: string, startDate: string, employeeCount?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpensePerEmployeeByTimeUsingPOST(endDate: string, startDate: string, employeeCount?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpensePerEmployeeByTimeUsingPOST(endDate: string, startDate: string, employeeCount?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (endDate === null || endDate === undefined) {
            throw new Error('Required parameter endDate was null or undefined when calling getExpensePerEmployeeByTimeUsingPOST.');
        }

        if (startDate === null || startDate === undefined) {
            throw new Error('Required parameter startDate was null or undefined when calling getExpensePerEmployeeByTimeUsingPOST.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (employeeCount !== undefined && employeeCount !== null) {
            queryParameters = queryParameters.set('employeeCount', <any>employeeCount);
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('endDate', <any>endDate);
        }
        if (startDate !== undefined && startDate !== null) {
            queryParameters = queryParameters.set('startDate', <any>startDate);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<Array<KeyValueResponse>>(`${this.basePath}/getExpensePerEmployeeByTime`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpensePerEmployee
     * 
     * @param employeeCount employeeCount
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpensePerEmployeeUsingPOST(employeeCount?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpensePerEmployeeUsingPOST(employeeCount?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpensePerEmployeeUsingPOST(employeeCount?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpensePerEmployeeUsingPOST(employeeCount?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (employeeCount !== undefined && employeeCount !== null) {
            queryParameters = queryParameters.set('employeeCount', <any>employeeCount);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<Array<KeyValueResponse>>(`${this.basePath}/getExpensePerEmployee`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
