/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { KeyValueResponse } from '../model/keyValueResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TravelControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getExpenseByBranch
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpenseByBranchUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpenseByBranchUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpenseByBranchUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpenseByBranchUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpenseByBranch`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpenseByBusinessArea
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpenseByBusinessAreaUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpenseByBusinessAreaUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpenseByBusinessAreaUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpenseByBusinessAreaUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpenseByBusinessArea`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpenseByCostCenter
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpenseByCostCenterUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpenseByCostCenterUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpenseByCostCenterUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpenseByCostCenterUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpenseByCostCenter`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpenseByDesignation
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpenseByDesignationUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpenseByDesignationUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpenseByDesignationUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpenseByDesignationUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpenseByDesignation`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpenseByEmployeeGrade
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpenseByEmployeeGradeUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpenseByEmployeeGradeUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpenseByEmployeeGradeUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpenseByEmployeeGradeUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpenseByEmployeeGrade`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getExpensePerEmployee
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpensePerEmployeeUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<KeyValueResponse>>;
    public getExpensePerEmployeeUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<KeyValueResponse>>>;
    public getExpensePerEmployeeUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<KeyValueResponse>>>;
    public getExpensePerEmployeeUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<KeyValueResponse>>(`${this.basePath}/getExpensePerEmployee`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
